spring.datasource.url=jdbc:postgresql://localhost:5432/crypto-trading
spring.datasource.username=crypto-trading
spring.datasource.password=changemelater!
spring.datasource.driver-class-name=org.postgresql.Driver